# Generated by Django 3.2.4 on 2021-06-25 13:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Course',
            fields=[
                ('cid', models.AutoField(primary_key=True, serialize=False)),
                ('course_name', models.CharField(max_length=30)),
                ('par', models.IntegerField()),
                ('slopevalue', models.IntegerField()),
                ('coursevalue', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Player',
            fields=[
                ('pid', models.AutoField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=30)),
                ('hcp', models.DecimalField(decimal_places=1, max_digits=3)),
            ],
        ),
        migrations.CreateModel(
            name='Round',
            fields=[
                ('rid', models.AutoField(primary_key=True, serialize=False)),
                ('score', models.IntegerField()),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.course')),
                ('player', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='frontend.player')),
            ],
        ),
    ]
