# Generated by Django 3.2.4 on 2021-06-25 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0002_alter_course_coursevalue'),
    ]

    operations = [
        migrations.AddField(
            model_name='round',
            name='date',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
