# Generated by Django 3.2.4 on 2021-06-25 13:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('frontend', '0004_alter_round_date'),
    ]

    operations = [
        migrations.AlterField(
            model_name='round',
            name='date',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
